Import('env')
imported_env = env
env = env.Clone()

srcs = 	[
	'main.cpp',
	'testApp.cpp',
]
srcs = map(lambda x: 'src/'+x, srcs)

env.AppendUnique(
	CPPPATH=['#ofxStructuredLight_lib/src'],
	LIBPATH=['#lib'],
	LIBS=['structuredLight'+env['DSUF']]
)

prog = env.Program('capture'+env['DSUF'], srcs)
env.Install('#OpenFrameworks_lib/apps/structuredLight/capture/bin', prog)
