Import('env')

env.SConscript('ofxControlPanel/SConscript', exports='env', duplicate=0)
env.SConscript('ofxQtVideoSaver/SConscript', exports='env', duplicate=0)
env.SConscript('ofxStructuredLight/SConscript', exports='env', duplicate=0)
